FROM node:21-alpine3.17

WORKDIR /app

COPY ./vue-app/package*.json /app/

RUN npm install -g vite
RUN npm install

COPY ./vue-app/ /app/
RUN npm run build

CMD npm run dev -- --port=8080 --host=0.0.0.0