version: '3'

services:
  laravel:
    container_name: "vibe-laravel"
    build:
      context: .
      dockerfile: Dockerfile-laravel
    volumes:
      - ./laravel-app:/var/www/html
    depends_on:
      - mysql

  vue:
    container_name: "vibe-vue"
    build:
      context: .
      dockerfile: Dockerfile-vue
    depends_on:
      - laravel

  nginx:
    container_name: "vibe-nginx"
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - laravel
      - vue
